name: 🚀 Deploy Website to All-Inkl

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3

    - name: 📦 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: 📦 Install Packages
      run: npm install
    
    - name: 🔨 Build
      run: |
        npm run build
    
    - name: 📦 Install Composer dependencies
      uses: php-actions/composer@v6
    
    - name: 📂 Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_AI }}
          REMOTE_USER: ${{ secrets.NAME_AI }}
          TARGET: ${{ secrets.PATH_AI }}
          EXCLUDE: "/node_modules/, /public/img/, /storage/, /public/static/, /public/storage/"